<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>UI\TechBroImage1.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="UI\TechBroImage.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="UI\TechBroImage.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\TechBroImage1.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.7-pre694" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.76.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.76.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.76.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.76.0" />
    <PackageReference Include="System.Management" Version="11.0.0-preview.4.26230.115" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="UI\MainWindow.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
